### ISSUE TITLE
This won't work as written, because Unix

### ISSUE THREAD

**Issue by unixnut** [jordansissel/shebang#1]
Great idea, but the limitation on passing a single arg plus the filename is baked into how exec*() works.  It will only read one argument from the shebang line in the script and run the interpreter with the following args:
- (arg 0) the interpreter filename
- the arg given on the shebang line, if any
- the script file name
- any args supplied on the script command line

Note that the 0th arg is not changed to the name of the script by exec(); the interpreter sets its own $0 variable and makes it available to the script.

To fix this, shebang should ignore its first command line argument.  Instead, it should open the script file itself (its second command line argument) and read all args from the shebang line, then add the rest of its command line arguments, then run the interpreter with the constructed arg list.

Note that there are two pathological cases where this will fail.  First: Unix supports only 1024 command line arguments, so if the number of args from the shebang line plus the number of command line args exceeds 1024, the exec() call will either fail or ignore the 1025th arg onwards.  Second: Unix supports only 1 mebibyte of command line, so a similar problem would occur but with number of characters instead.

**Comment by jordansissel** [comment]
I confess I didn't read much past the "This won't work" subject. It worked for my needs at the time (which was several years ago), and a quick test now shows me it indeed still works (tested on Fedora 23).

**Comment by unixnut** [comment]
Can you post a gist with your test code, please? I will do likewise when I get a chance.
